# 2018.3.23

Today tasks:
1. Deeplearning.ai CNN first week homework
2. TensorFlow Tutorial

## Note

**Exercise**: Implement the following function, which pads all the images of a batch of examples X with zeros. [Use np.pad](https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html). Note if you want to pad the array "a" of shape $(5,5,5,5,5)$ with `pad = 1` for the 2nd dimension, `pad = 3` for the 4th dimension and `pad = 0` for the rest, you would do:
```python
a = np.pad(a, ((0,0), (1,1), (0,0), (3,3), (0,0)), 'constant', constant_values = (..,..))
```

np 实现 conv
```python 
s = np.multiply(W, prev)
Z = np.sum(s)
Z = Z + b
```

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
i = 0
print(a[i: i+2])
print("***")
print(a[i+2 : ])

[[1 2 3]
 [4 5 6]]
***
[[7 8 9]]
